import { POST } from "@/app/api/confession/create/route";

export const QUERY_KEYS = {
  SEND_OTP: "SEND_OTP",
  VERIFY_OTP: "VERIFY_OTP",
  CREATE_PROFILE: "CREATE_PROFILE",
  GET_USER: "GET_USER",
  GET_ALL_CONFESSIONS: "GET_ALL_CONFESSIONS",
  GET_DASHBOARD_DATA: "GET_DASHBOARD_DATA",
  GET_ALL_NEWS: "GET_ALL_NEWS",
  CREATE_NEWS: "CREATE_NEWS",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  GET_PROFILE: "GET_PROFILE",
  GET_ALL_COMMENTS: "GET_ALL_COMMENTS",
  LIKE_POST: "LIKE_POST",
  POST_COMMENT: "POST_COMMENT",
  CHECK_FOR_ME  : "CHECK_FOR_ME",
};
