export const SP_DEDUCTION = {
    CHECK_FOR_ME:5,
    REVEAL_IDENTITY:299
}

export const SP_REWARD = {
    COMMENT:2,
    POST_NEWS:5,
    LIKE:2,
    REFER:20,
    POST_CONFESSION:5,
    POST_NEWS_WITHOUT_IMAGE:5,
    POST_NEWS_WITH_IMAGE:10,
}